### ISSUE TITLE
Cannot import NameError: name 'CLIPTemperaturePatch' is not defined

### ISSUE THREAD

**Issue by whmc76** [Extraltodeus/ComfyUI-AutomaticCFG#32] opened 2024-05-23 08:37 UTC
Traceback (most recent call last):
  File "E:\IMAGE\ComfyUI_slave\ComfyUI\nodes.py", line 1879, in load_custom_node
    module_spec.loader.exec_module(module)
  File "<frozen importlib._bootstrap_external>", line 940, in exec_module
  File "<frozen importlib._bootstrap>", line 241, in _call_with_frames_removed
  File "E:\IMAGE\ComfyUI_slave\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG\__init__.py", line 19, in <module>
    "Temperature settings CLIP": CLIPTemperaturePatch,
                                 ^^^^^^^^^^^^^^^^^^^^
NameError: name 'CLIPTemperaturePatch' is not defined

Cannot import E:\IMAGE\ComfyUI_slave\ComfyUI\custom_nodes\ComfyUI-AutomaticCFG module for custom nodes: name 'CLIPTemperaturePatch' is not defined

**Comment by VJaGG** [comment] 2024-05-23 09:39
Add to __init__ file
`from .experimental_temperature import ExperimentalTemperaturePatchSDXL,ExperimentalTemperaturePatchSD15, CLIPTemperaturePatch`

**Comment by GalaxyTimeMachine** [comment] 2024-05-23 13:43
Duplicate of #31

**Comment by Extraltodeus** [comment] 2024-05-24 22:25
Yeah sorry I forgot to add it, should be good now!

**Closed by Extraltodeus** 2024-05-24 22:25 UTC
